# Generated by Django 3.0.2 on 2020-01-21 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TH_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField()),
                ('run_time', models.IntegerField()),
                ('run_time_str', models.CharField(max_length=10)),
                ('run_time_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TH_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField()),
                ('run_time_str', models.CharField(max_length=10)),
                ('last_run_id', models.IntegerField()),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('max_hum_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('max_hum', models.FloatField()),
                ('max_hum_temp', models.FloatField()),
            ],
        ),
    ]
