# Generated by Django 2.1 on 2020-01-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='th_data',
            name='run_time',
            field=models.IntegerField(),
        ),
    ]
